### ISSUE TITLE
Smart Port

### ISSUE THREAD

**Issue by marwand** [jcheger/frsky-arduino#4]
Hello jcheger,

This is more of a question than an issue and I apologize for contacting you this way. I was wondering if the arduino can read rpm without having the smart port connected. I have an eagle tree brushless rpm sensor and everything is connected according to the diagram provided (except the smart port) and I'm getting no output from the arduino. I suspect that the smart port is needed because of the line [FrskySP FrskySP (10, 11);]. Also, is all the decoding happening through the smart port? Is there any way around it? Finally, can I get more information about the smart port? 

Thank you very much & I appreciate your help.

**Comment by jcheger** [comment]
Hi marwand,

The smartport use a cyclic pull of addresses, which triggers the answer. 
But you don't want this.

The EagleTree RPM sensor gives a pulse at every rotation. It is very 
basic, as any hall effect or optical sensor does.

Here is some part of code I did write for a simple RPM counter. I've 
modified it to print the RPM on serial once per second. I think it will 
fit better you needs.

Regards, Jean-Christophe Heger

#define RPM_PIN 2

unsigned long sum = 0;
unsigned long count = 0;

void setup() {
   Serial.begin (115200);
   pinMode (RPM_PIN, INPUT);
   attachInterrupt (0, rpmISR, RISING);
}

void loop() {
   float freq;
   unsigned int rpm;

   delay (1000);
   detachInterrupt (0);

   freq = (sum) ? ((float) count \* 1000000.0 / (float) sum) : 0.0;
   rpm = int (freq \* 6.0) \* 10;
   Serial.println (rpm);
   sum = 0;
   count = 0;

   attachInterrupt (0, rpmISR, RISING);
}

void rpmISR () {
   static unsigned long last_micros = 0;

   if (last_micros) {
     sum += micros () - last_micros;
     count++;
   }

   last_micros = micros ();
}

**Comment by marwand** [comment]
Thanks a lot man. Hope you're enjoying your holidays!
